#! /bin/bash

path=$(pwd)"/$1"
cd ~/Desktop/nand2tetris/projects/06/assembler/build/
rm -rf *
echo
echo "Starting Assembler......"
echo
cmake .. > /dev/null
echo "Loading File....."
echo
make > /dev/null
echo
./system $path
cd - 1> /dev/null
echo
